/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mark.mark1;

public class App {
    public int multiply(int num1, int num2){
        return num1*num2;
    }

    public static void main(String[] args) {
    }
}

