/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mark.mark1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
       assertEquals(6, classUnderTest.multiply(2, 3));
    }
}
